[package]
name = "rust_raw_file_access"
version = "0.1.0"
authors = ["taturou <taturou@gmail.com>"]
links = "rawopen"
build = "build.rs"

[dependencies]
libc = "0.2.0"

[build-dependencies]
gcc = "0.3"
